### ISSUE TITLE
Move out more languages

### ISSUE THREAD

**Issue by Albinutte** [CodeSignal/dockerfiles#11]
Migrating issue https://github.com/CodeSignal/coderunner/issues/91 here. This issue includes moving more languages out to separate docker files.

## Languages to Support
- [x] Bash     (ubuntu-base)
- [x] C    (cpp)
- [x] Clojure
- [x] Coffeescript
- [x] C#    (csharp)
- [x] C++      (cpp)
- [x] D
- [x] Dart
- [x] Erlang
- [x] Elixir
- [x] F#   (csharp)
- [x] Fortran (cpp)
- [x] FreePascal
- [x] Go
- [x] Groovy 
- [x] Haskell    (haskell)
- [x] Java     (java)
- [x] Javascript      (ubuntu-base)
- [x] Julia
- [x] Kotlin
- [x] Lisp
- [x] Lua
- [x] Mysql     (ubuntu-base)
- [x] Nim
- [x] ObjectiveC     (swift)
- [x] Octave     (octave)
- [x] OCaml       (ocaml) 
- [x] Perl
- [x] Php        (php)   
- [x] Postgresql
- [x] Python      (python)
- [x] Python3      (python)
- [x] R       (r)
- [x] Ruby
- [x] Rust
- [x] Scala
- [x] Smalltalk       (smalltalk)  
- [x] Swift       (swift)
- [x] Tcl       (tcl)
- [x] Typescript
- [x] VB
- [x] Rspec

**Comment by menewman** [comment]
@ksaxberg - Please look through again and clarify which shouldn't be done because they're covered elsewhere (e.g., Typescript)

To developer taking this:
In scope is handling the remaining languages here.

**Comment by ksaxberg** [comment]
Marked off all the ones that have been done / have outstanding PRs for, leaving 11 languages left.
