### ISSUE TITLE
Add sklearn support to Python Dockerfile

### ISSUE THREAD

**Issue by menewman** [CodeSignal/dockerfiles#116]
sklearn is a popular/free machine learning-related library.

As a follow-up, create an issue/PR in the coderunner repo updating the Docker image version as well.

**Comment by eduard-piliposyan** [comment]
I see that we already have support for `scikit-learn` https://github.com/CodeSignal/dockerfiles/blob/ae29dbb0029cbc6ace91afe09db5635b6dfbbb3a/python/Dockerfile#L20
I believe sklearn is the same as scikit-learn.
@menewman Closing this task. Feel free to reopen if you have some other context about this and something else should be added as well.

**Comment by menewman** [comment]
kk, will also close your associated customer request, then
