### ISSUE TITLE
Auto-build dependent Docker images for non-master branches

### ISSUE THREAD

**Issue by Albinutte** [CodeSignal/dockerfiles#121]
Adding a CI that will build a new image on dockerhub for every non-master branch based on the changed Dockerfile will save a crazy amount of time, especially when updating the entire tree of dockerfiles.

In an ideal world. whenever I open a pull request that changes a Dockerfile for language `X`, the image for `X` will be built on dockerhub, either with `dev` or `<branch_name>` tag. Something like what is described [here](https://circleci.com/blog/using-circleci-workflows-to-replicate-docker-hub-automated-builds/).

**Comment by menewman** [comment]
Willing to prio since we're in a technical phase right now. Re-phrased the title to describe the problem instead of the suggested solution.
