### ISSUE TITLE
Builds fail because of invalid Mongo GPG key

### ISSUE THREAD

**Issue by menewman** [CodeSignal/dockerfiles#123]
Was trying to add some Regex libraries to Haskell but the build fails, even if no substantive changes have been made:
https://hub.docker.com/repository/registry-1.docker.io/codesignal/haskell/builds/c1e9dde5-2454-4aad-b56e-27f03840283f

Specifically, this is what it shows:
```
Reading package lists...
[91mW: GPG error: https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.0 Release: The following signatures were invalid: BADSIG 68818C72E52529D4 MongoDB 4.0 Release Signing Key <packaging@mongodb.com>
W: The repository 'https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.0 Release' is not signed.
```

I think we likely just need to update the key, since the old one must be invalid or expired in the base image somehow:
https://stackoverflow.com/a/46710352
https://www.digitalocean.com/community/tutorials/how-to-install-mongodb-on-ubuntu-16-04#step-1-%E2%80%94-adding-the-mongodb-repository

Unfortunately, that would mean that we'd need to update the base image.

**Comment by menewman** [comment]
@Albinutte - Just checking, you haven't seen this error in any builds while continuing to re-build dependent images after the MySQL update? Was it just me?

**Comment by Albinutte** [comment]
@menewman I haven't! Maybe there was a one-time network issue?

**Comment by menewman** [comment]
Curiouser and curiouser...

**Comment by Albinutte** [comment]
@menewman I believe everything's fine with mongo. Check out [this](https://circleci.com/gh/CodeSignal/dockerfiles/69) build: it got completed successfully. If you're okay with that, I would just close this issue and move on to the next one :slightly_smiling_face:

**Comment by menewman** [comment]
I'm more than okay with that... I'm relieved.
