### ISSUE TITLE
Hello, I want to know what version of coffeescript is in your docker image?

### ISSUE THREAD

**Issue by RanX12** [CodeSignal/dockerfiles#135]
Hello, I want to know what version of coffeescript is in your docker image? Thanks.
Is it CoffeeScript version 2.5.1, if not, how much is it?
https://hub.docker.com/r/codesignal/coffeescript

**Comment by Albinutte** [comment]
Hey @RanX12! CoffeeScript version in the [coffeescript](codesignal/coffeescript) docker image is `CoffeeScript version 2.5.1`.

**Comment by menewman** [comment]
Thanks for responding to that, @Albinutte, and hope that helps, @RanX12! Closing this issue since it's an answered question.
