### ISSUE TITLE
Can anybody create PR to update programming language version?

### ISSUE THREAD

**Issue by ulugbekna** [CodeSignal/dockerfiles#144]
Hi,

1. Do I understand correctly that ordinary people (non codesignal team member) can contribute to this repo to update the language version available on codesignal? 
2. If yes to (1), is pulling shell files (from an official and credible source, of course) is ok in the dockerfile? 

I would like to update OCaml to 4.09. I will follow the official instruction to install Opam (ocaml package manager) and then install ocaml using opam. 

Thanks!

**Comment by menewman** [comment]
@ulugbekna - Hi! Sure, we'd welcome your contribution in submitting such a PR. 👍 

We do have some things in non-public repos that will need to be updated/tested before we can ship an updated language version (we use language-specific templates for some of our functionality),  so we'd greatly appreciate if you document any breaking changes you can find between the versions to make that template update as seamless as possible.

> If yes to (1), is pulling shell files (from an official and credible source, of course) is ok in the dockerfile?

Depends on context, but if it's the generally accepted way to install OCaml on Ubuntu then it's probably okay.

**Comment by menewman** [comment]
I'm going to close this as it isn't really an issue to track, but @ulugbekna, thanks for asking and feel free to continue the discussion or ask any follow-up questions as needed!
