### ISSUE TITLE
codesignal/acceptance-tests latest versions are not working

### ISSUE THREAD

**Issue by salbert96** [CodeSignal/dockerfiles#169]
The latest versions of `codesignal/acceptance-tests` are failing coderunner tests.

We're using an older version of this image (v5.5) that does pass the tests, similar to what we do for the Objective-C image.

**Comment by menewman** [comment]
@salbert96 - You mean, after updating the versions from your latest PRs? The tests were passing on the latest deployed version of the images.

**Comment by menewman** [comment]
We're going to assume the former and send this directly to you, but please clarify if we misunderstood!

**Comment by salbert96** [comment]
The image was not updated the last time ubuntu-base was updated.
The version is `codesignal/acceptance-tests:v5.5` in coderunner, but the last ubuntu base change was `v5.6` I am not sure if it would pass with version 5.6 but I did not go into the details of that image.

I would prefer to move it to the icebox for now, since it would be better to do this after persistent sessions.

**Comment by salbert96** [comment]
@menewman ^^

**Comment by menewman** [comment]
I see! Removing your assignment then

**Comment by ArDrambyan** [comment]
Resolved in the sope of #288
