### ISSUE TITLE
P.Session: Install vim and GNU Debugger

### ISSUE THREAD

**Issue by salbert96** [CodeSignal/dockerfiles#183]
We can install vim and GNU Debugger on `ubuntu-base` so that they can be used from the terminal without requiring additional installations. @menewman this is not a high priority one but I would love to know your opinion.

**Comment by menewman** [comment]
Unless vim and GNU debugger are a lot bigger than I think they are, I don't have an objection. My first instinct (I guess after basic commands like `ls`) with the terminal was to run `vim`, so it makes sense to me.

I do think encouraging vim use from the terminal without properly syncing back file changes to our editor will expose that problem a little more, but that's not really a reason not to install it.
