### ISSUE TITLE
[Content] Add Django library for Python2/3

### ISSUE THREAD

**Issue by Anastasiya-Zhyrkevich** [CodeSignal/dockerfiles#196]
We want to experiment with filesystem tasks for Django 
We need to have library installed.

`python -m pip install Django`

https://docs.djangoproject.com/en/3.1/topics/install/

**Comment by Albinutte** [comment]
I'm going to open a PR for experementation purposes, and download the built image on some coderunner to play around with it. Let me know if you'd like to keep the changes!

**Comment by Albinutte** [comment]
Looks like this package is not that big, so we can just go ahead and install it.
