### ISSUE TITLE
P.Session: Install interactive shell for TypeScript

### ISSUE THREAD

**Issue by salbert96** [CodeSignal/dockerfiles#199]
Here are my experiments with the terminal.
![Screen Shot 2020-09-08 at 21 13 18](https://user-images.githubusercontent.com/29372842/92507561-3c1ea680-f218-11ea-8db3-c0590f87e3f5.png)
We can use the `ts-node` package for it. Other platforms use that too.
https://github.com/TypeStrong/ts-node

**Comment by eduard-piliposyan** [comment]
@salbert96 Did I get right that there is a very good workaround for this, by just installing the required tool?

**Comment by salbert96** [comment]
@eduard-piliposyan it is always possible to install anything from the terminal. I do think that the right approach is to have these packages pre-installed but if you want you can icebox these issues feel free to do it, I will get back to them after the terminal replay (or during the code-review phase). Please don't remove the estimate though 🙂 so that I can easily move them later.

**Comment by salbert96** [comment]
Seems like the issue was fixed here
https://github.com/CodeSignal/dockerfiles/pull/200
Right the next day that this issue was created 😅
