### ISSUE TITLE
Fix failing OpenCV build

### ISSUE THREAD

**Issue by menewman** [CodeSignal/dockerfiles#211]
OpenCV used to build on DockerHub, but lately it's been failing there and all builds have been done locally and pushed to DockerHub. What's the deal with that? Can we fix it?

**Comment by Albinutte** [comment]
I'm afraid the image was never built on the CI, or at least not its very first version 😅  Here's the PR that introduced the image: #129. As I mentioned in the description there:

> ... automated OpenCV build probably failed because dockerhub couldn't handle it. I built the image manually and pushed it to dockerhub, and it's working, I guarantee it.

**Comment by menewman** [comment]
Thanks for correcting my assumption that this used to work! That makes me feel both better and worse. 🤔

**Comment by menewman** [comment]
I checked and I don't think we have any tasks using OpenCV right now. But, we did sign Niantic, who was the company who asked for this. Not sure how that makes me feel about priority of this task.
