### ISSUE TITLE
Support mssql in ubuntu-base

### ISSUE THREAD

**Issue by salbert96** [CodeSignal/dockerfiles#220]
Right now we have a separate image for `mssql`, let's see if we can support mssql in ubuntu-base too.
The last time we tried we had problems with memory and storage. This is for experimenting and understanding what it would look like if we wanted to support it in ubuntu-base.
Here is a discussion about it.
https://github.com/CodeSignal/coderunner/pull/862#issuecomment-730351432
Let's still keep the discussions in coderunners to make sure it is private.

**Comment by menewman** [comment]
@salbert96 - My understanding was that @mpowaga got Microsoft SQL Server running in ubuntu-base already, right, and we were just worried about the disk and/or memory usage? In that case, assuming that this server software doesn't get any smaller, what's the path forward on this issue?

Should we close it in favor of an issue like "figure out how to run database servers separately from the language-environment Docker images"?

**Comment by menewman** [comment]
Lemme tag the whole gang here: @Albinutte @eduard-piliposyan

**Comment by salbert96** [comment]
I wanted for us to move fast so we decided to go with a separate image. @mpowaga managed to install it on ubuntu-base but supporting it there would be complicated since we had to update all the other images. I created this issue so that one researches and understands what are the challenges of disk/memory usage if we consider supporting it in ubuntu-base.
I generally don't like that we install such things in ubuntu-base and would prefer that we had separate images, but I guess we are far from supporting it.
I am open to both solutions, I guess it depends on client requests. If the clients want to use MsSQL in other languages then we can install it.

**Comment by Albinutte** [comment]
> Should we close it in favor of an issue like "figure out how to run database servers separately from the language-environment Docker images"?

I like this approach way more than going back to the "mega-base-docker", and I think it will be more scalable. If, for example, we have a separate pool of containers with database servers exposed to the host, then it should be possible for the language-specific containers to access the servers running from other containers.

**Comment by menewman** [comment]
> I like this approach way more than going back to the "mega-base-docker", and I think it will be more scalable. If, for example, we have a separate pool of containers with database servers exposed to the host, then it should be possible for the language-specific containers to access the servers running from other containers.

Yep, I was thinking along the same lines. Lemme open a new issue in the coderunner repo to track.
