### ISSUE TITLE
Create a new base image derived from Ubuntu 20+

### ISSUE THREAD

**Issue by menewman** [CodeSignal/dockerfiles#233]
Ubuntu 16 LTS reaches end of standard support in April this year (although it's not EOL yet -- not until 2024). Some packages are harder to install on 16, since it's not the latest anymore.

Let's upgrade our base image to Ubuntu 20! That's the latest stable/LTS version. This will require a lot of cascading changes, so ideally I think we should do it in a way where we can make the upgrade in parallel to our existing Ubuntu 16 images.

**Comment by ArDrambyan** [comment]
Oh, I missed this issue. 
I'm going to close this in favor of [#276](https://github.com/CodeSignal/dockerfiles/issues/276) Epic
