### ISSUE TITLE
Update ubuntu-base image to support new Ubuntu version

### ISSUE THREAD

**Issue by ArDrambyan** [CodeSignal/dockerfiles#234]

**Comment by menewman** [comment]
I want to copy from the issue I wrote about this (#233):
> Ubuntu 16 LTS reaches end of standard support in April this year (although it's not EOL yet -- not until 2024). Some packages are harder to install on 16, since it's not the latest anymore.

> Let's upgrade our base image to Ubuntu 20! That's the latest stable/LTS version. This will require a lot of cascading changes, so **ideally I think we should do it in a way where we can make the upgrade in parallel to our existing Ubuntu 16 images**.

Emphasis added. As a first step for this migration, in addition to actually upgrading the base image, I think it would be great to discuss and agree on the high-level strategy for updating to Ubuntu 20+.

**Comment by ArDrambyan** [comment]
After discussion, I and @menewman decided to create a separate branch for the whole Ubuntu version update and when all images will be updated we will merge that branch into the master. The main branch will be called `276-ubuntu-version-20` and other branches can be called `<issue-name>-<image-name>-ubuntu-version-20` for consistency

**Comment by ArDrambyan** [comment]
I'll write a small confluence doc on how to update and test dockerfiles and will attach it to epic
