### ISSUE TITLE
Update cpp image to support new Ubuntu version

### ISSUE THREAD

**Issue by ArDrambyan** [CodeSignal/dockerfiles#236]

**Comment by ArDrambyan** [comment]
I think [#925](https://github.com/CodeSignal/coderunner/issues/925) can be in the scope of this issue

**Comment by eduard-piliposyan** [comment]
https://codesignal.atlassian.net/wiki/spaces/PE/pages/945946690/How+to+update+docker+images+to+Ubuntu+20.04
