### ISSUE TITLE
Update Ubuntu version to 20.04

### ISSUE THREAD

**Issue by ArDrambyan** [CodeSignal/dockerfiles#276]
We started to face issues while updating compilers because of our ubuntu version. It is 16.04 and the support ends this April, so we need to update our Ubuntu version to be safe from OS problems for the next few years. `Ubuntu 20.04` is the latest available major version so it will our target.

**Comment by ArDrambyan** [comment]
attaching confluence doc for easier development: https://codesignal.atlassian.net/wiki/spaces/PE/pages/945946690/How+to+update+docker+images+to+Ubuntu+20.04

**Comment by menewman** [comment]
[From backlog grooming] Directly assigning this since it seems like the child issues are done

**Comment by ArDrambyan** [comment]
Finally, all dockerfiles are updated and coderunner now used Ubuntu 20 based dockerfiles
