### ISSUE TITLE
Remove 'Main' / 'Common' Container

### ISSUE THREAD

**Issue by ksaxberg** [CodeSignal/dockerfiles#32]
Depends on #28 

After splitting out the Galen container, comb through the `main` dockerfile and make sure we have covered all of the dependencies in other containers. Also make sure that all of our languages / frameworks from the coderunners repo are selecting sensible containers to be run in (should be nearly complete, but just double check before removing the best fallback container we have!)

Re-enable the `swift4` test!

Also remove the main container from the Install scripts.

**Comment by Albinutte** [comment]
@menewman any chance we can slide this into this week's deploy? This is the very last step in the dockerfiles rework project, and since #28 is ready we can finally do this.

**Comment by menewman** [comment]
It's a Rundash + coderunner-only deploy, right? Is there anything that needs to hit the main app?

**Comment by Albinutte** [comment]
@menewman right! No changes to the main app necessary.

**Comment by menewman** [comment]
Great.

Let's just figure out what still needs to be merged (the Galen container PR, and maybe some PRs in the coderunner repo?), and try to redeploy Rundash + new coderunner versions by EOD Tuesday, assuming everything is reviewed/ready to go. Then Aida can test the new coderunner versions implicitly and we can roll out the same versions to prod later in the week.

**Comment by Albinutte** [comment]
Actually sorry, for the initial version we don't even need to redeploy Rundash, and let all coderunners handle both Galen and regular requests just like we do it now. So the checklist is:
1) Get Galen PR merged;
2) Publish all updated dockerfiles, and remove `main` one;
3) Update `coderunner` code to pull and use all those dockerfiles.

**Comment by menewman** [comment]
@Albinutte - I thought there was a breaking change where new coderunner versions have to be deployed by a new Rundash version, though? The new setup script?

**Comment by Albinutte** [comment]
@menewman oh yeah, sorry, forgot about that change. Yup, Rundash also needs to be redeployed then.

**Comment by menewman** [comment]
Also did you know this whole discussion is public because it's an open repo. 👀

**Comment by Albinutte** [comment]
![](https://media.giphy.com/media/HUkOv6BNWc1HO/giphy.gif)
