### ISSUE TITLE
Bump Go version 

### ISSUE THREAD

**Issue by KARM99** [CodeSignal/dockerfiles#347]
Ubuntu 20.04 comes with go version 1.16. Just simple `apt-get update && apt-get install golang-go` should do the trick.

**Comment by menewman** [comment]
Good news! This is implicitly already done as part of our Ubuntu 20 migration. It will be shipped automatically when we release that version of our Dockerfiles:
![Screen Shot 2021-03-29 at 10.16.01 AM.png](https://images.zenhubusercontent.com/5cb4bdc9d74bd07972cedee3/5250e656-22a4-486f-b6d2-07d05d6cba2b)
