### ISSUE TITLE
Add a Gravatar

### ISSUE THREAD

**Issue by ksaxberg** [CodeSignal/dockerfiles#38]
We should add a [Gravatar](https://en.gravatar.com/) and add the email [here](https://hub.docker.com/u/codesignal/dashboard/settings/) so that we can show off our company logo on Dockerhub.

**Comment by menewman** [comment]
sure why not

![screen shot 2018-11-09 at 11 05 57 am](https://user-images.githubusercontent.com/747378/48282781-7bf38780-e40f-11e8-8f6b-07bea2d8fdf1.png)
