### ISSUE TITLE
Add support for Flutter

### ISSUE THREAD

**Issue by iamhrayr** [CodeSignal/dockerfiles#414]
Add Dockerfile to be able run/build flutter applications

**Comment by artiomisfowl** [comment]
@iamhrayr Does this issue take care of https://app.asana.com/0/417895759505117/1199099456865997? Thanks!

**Comment by iamhrayr** [comment]
@artiomisfowl yes, but Flutter support is divided into several GitHub issues. The other 2 ones will be done very soon -   https://github.com/CodeSignal/codesignal/issues/21731, https://github.com/CodeSignal/coderunner/issues/1501

**Comment by artiomisfowl** [comment]
Thanks @iamhrayr! Sounds great to me.
