### ISSUE TITLE
Add mongodb to base image

### ISSUE THREAD

**Issue by ksaxberg** [CodeSignal/dockerfiles#42]
Add mongodb to the base image, update all dependencies to reference this new image.

**Comment by ksaxberg** [comment]
This may be a little involved as this requires running the `mongod` service to start docker, and setting up the `mongodb` user accounts / default data folders.

Can't really leverage the official `mongo` docker containers because they utilize an entrypoint to get the job done and our base image can't have an entrypoint. (it would automatically run that code instead of command line args, which is how we actually execute user code).

**Comment by Albinutte** [comment]
> this requires running the mongod service to start docker, and setting up the mongodb user accounts / default data folders.

I guess we need a `mongod_runner.sh` file similar to what we have for Postgres / Mysql (e.g. [this](https://github.com/CodeSignal/coderunner/blob/master/API/Payload/postgresql_runner.sh))?
