### ISSUE TITLE
Bump up Scala version to v3.1.0

### ISSUE THREAD

**Issue by ArDrambyan** [CodeSignal/dockerfiles#430]
Our current `Scala` version is `v2.12.10` while `v3.1.0` is already available

**Comment by artahian** [comment]
@menewman do you think this issue is still blocked by the Java/Gradle issue that we iceboxed? I wonder if we can still do this without the Gradle switch?

**Comment by menewman** [comment]
I think this can be done separately -- good call. I removed the dependency

**Comment by Albinutte** [comment]
FYI: this is a major version upgrade, so there will be a few breaking changes. I don't expect many of the existing solutions to be affected (while testing I had to make a single tiny change to the template code, and no changes whatsoever to the test code), but it might still be a good idea to show upgrade notification on the website upfront.
