### ISSUE TITLE
Python2 and Python3 error while trying to build

### ISSUE THREAD

**Issue by miamagana** [CodeSignal/dockerfiles#445]
Updating base image to resolve #441 we found out that Python images are not building correctly due to a dependency.

Screenshot of the error is attached.

<img width="1023" alt="Captura de pantalla 2022-01-28 a las 7 56 18" src="https://user-images.githubusercontent.com/47744264/151501584-85302090-1d55-4b9c-9a2d-d2dc945b78ed.png">

## Steps to reproduce

1. Change python's base image to v9.6 instead of v9.4
2. docker build .
3. The error is thrown

**Comment by menewman** [comment]
Python 2.7 errors are more "expected" to me for dependency versions that aren't pinned, in which case the fix is just to pin the version... but if it's for Python 3 too, that's not good!

**Comment by miamagana** [comment]
I will investigate this issue this week and let it sorted out 👍
