### ISSUE TITLE
Bump up dotnet to v6 or higher

### ISSUE THREAD

**Issue by lizhoucheng** [CodeSignal/dockerfiles#462]
### Context

https://app.asana.com/0/417895759505117/1202150148944472/f
- Requested by: Dropbox 🦄 
- Dropbox is asking to upgrade our .NET version from 3.1 to 6 in order build out a filesystem task for an Interview question.

**Comment by Albinutte** [comment]
This might also require changes in our main app to change the default starter code for .NET projects.
