### ISSUE TITLE
Upgrade MySQL to a 8+ version

### ISSUE THREAD

**Issue by aramshat** [CodeSignal/dockerfiles#57]
Glu Mobile had a bad experience using our database tasks and one of the biggest issues was that their candidates weren't able to use window functions (http://www.mysqltutorial.org/mysql-window-functions/) that are introduced in recent MySQL versions. Our current version seems to be too old (5.x) so we should upgrade it to 8.0 or higher to support these. Glu Mobile claims that it is a pretty standard approach, in particular for a Data Analyst to use.

**Comment by Albinutte** [comment]
@aramshat 

ALRIGHTY. I've spent quite some time looking into MySQL 8.0, and I can't figure out how to make it work in a way that's backwards compatible with the existing DevOps tasks. Updating base image seems to be too complicated to be worth it.

As far as I understand, Glu Mobile only uses database tasks, but not devops tasks. What if we upgrade only stand-alone MySQL version? It will remain 5.7 in all containers, but MySQL-specific tasks will have a dedicated docker image with version 8.0.
