### ISSUE TITLE
Add git

### ISSUE THREAD

**Issue by menewman** [CodeSignal/dockerfiles#62]
@RubenAshughyan says:
> Right now I am working on a task feature requested by OnceHub.
> https://github.com/CodeSignal/content/issues/4018
> The special aspect of the task is that the user needs to use git in the solution. Unfortunately, git is not a part of linux as a default, and in order to support git commands while judging tasks in coderunners we need to include git while making docker images.

Seems like we should add it, probably to the base image! That content issue has a hard deadline of July 30-31, so let's try to target July 26 deploy for this.

**Comment by Albinutte** [comment]
> probably to the base image

Oh boi.
