### ISSUE TITLE
Builds failed for Dart, Lisp, and Python for some reason

### ISSUE THREAD

**Issue by rowena000** [CodeSignal/dockerfiles#69]
Related to #62.
We updated the base image and published a tag `based-on/ubuntu-base/v5.0`, which triggered builds for languages depending on the base image. For some reason, it failed for the Dart, Lisp, and Python.
Related builds:
Dart: https://cloud.docker.com/u/codesignal/repository/registry-1.docker.io/codesignal/dart/builds/f00ccfbb-3743-4fb5-ba41-365dc362fc63

Lisp: https://cloud.docker.com/u/codesignal/repository/registry-1.docker.io/codesignal/lisp/builds/e09b0372-8f93-4fa0-96ff-23dcb43e4479

Python: https://cloud.docker.com/u/codesignal/repository/registry-1.docker.io/codesignal/python/builds/ab1cf160-ed91-4c92-bef3-eba7d35fcbed

**Comment by Albinutte** [comment]
Based on build errors, these sound like three very separate issues to me.

**Comment by Albinutte** [comment]
Closing in favor of opened separate issues.
